# Generated by Django 3.2.5 on 2021-08-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210811_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
    ]
